### ISSUE TITLE
Only the latest hook will get triggered

### ISSUE THREAD

**Issue by kjin** [elastic/require-in-the-middle#11]
I think this line is causing a second hook to override a first:

https://github.com/elastic/require-in-the-middle/blob/fb286a90897c10e153feeda5aa157ed6ed659c56/index.js#L43

**Comment by watson** [comment]
Ah yes, I think you're spot on. This is because `Module.prototype.require` isn't [overwritten](https://github.com/elastic/require-in-the-middle/blob/fb286a90897c10e153feeda5aa157ed6ed659c56/index.js#L26) in the same tick as when we're [caching the original function](https://github.com/elastic/require-in-the-middle/blob/fb286a90897c10e153feeda5aa157ed6ed659c56/index.js#L8).

If we just moved that into `hook` function then I think it would all work as expected 😃

**Comment by watson** [comment]
This have now been fixed in v3.0.0

**Comment by kjin** [comment]
Thanks!

**Comment by watson** [comment]
This have now been released in elastic-apm-node v1.8.1 as well
