### ISSUE TITLE
Need to increment git ignore configuration

### ISSUE THREAD

**Issue by robertosousa1** [elastic/require-in-the-middle#47]
It is a good practice to increase the configuration of .gitignore with files that have no direct value to the application in addition to simply adding node_modules as it currently is.

#### For example, add the following files:
logs
*.log
npm-debug.log*
pids
*.pid
*.seed
.idea

**Comment by astorm** [comment]
Howdy @robertosousa1 -- nice to meet you and thanks for for the suggestion!

That said we're going to close this one out.  We prefer to grow out `.gitignore` files organically out of need rather than attempt to guess what what sort of ignorable files might be a part of someone's workflow.  

In general for our repos -- if you're working on PRs and find the need i ignore something, adding it to the `gitignore` along with the PR is the way to go.

**Comment by robertosousa1** [comment]
I understand. Thanks!!!
