### ISSUE TITLE
tests are failing for node v6.0.0 because @babel/preset-env@^7.9.5 cannot be installed with npm 3.8.6

### ISSUE THREAD

**Issue by trentm** [elastic/require-in-the-middle#48]
https://travis-ci.org/github/elastic/require-in-the-middle/jobs/744039652

```
% nvm use 6.0.0
Now using node v6.0.0 (npm v3.8.6)

% npm --version
3.8.6

% cat package.json
{
  "name": "clean",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/preset-env": "^7.9.5"
  }
}

% npm install
npm ERR! Darwin 19.6.0
npm ERR! argv "/Users/trentm/.nvm/versions/node/v6.0.0/bin/node" "/Users/trentm/.nvm/versions/node/v6.0.0/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /Users/trentm/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/trentm/tmp/clean/npm-debug.log
```

The install works fine with the npm included with node v6.9.0 (which is the [min node version supported by babel currently](https://github.com/babel/babel/blob/b9deeb458baf160f191d95d15e80c092cf8c2ce2/package.json#L85)).

The current min version for this module (by inference from .travis.yml) is v6.0.0. Testing against the initial v6 release was added in https://github.com/elastic/require-in-the-middle/pull/33

## options

1. Drop @babel/register support (added in https://github.com/elastic/require-in-the-middle/pull/39) in v5. Not a real solution given there is a release with this support.
2. Somehow hack to not attempt to install and test the babel support with using node v6. That seems like an excessive amount of work.
3. Drop node v6 support, and bump the major ver to require-in-the-middle@6 and just move on. This is my preference.

Note that I haven't yet suggested dropping node v8 support because the main consumer (elastic/apm-agent-nodejs) still supports node v8 for its current major version.

**Comment by rskokate** [comment]
D:\Ratnadip\Projects\ecomm-gnc-sfcc\gulp_builder>npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm ERR! Windows_NT 10.0.19042
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:455:12)
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:456:7
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:134:20)
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Ratnadip\Projects\ecomm-gnc-sfcc\gulp_builder\npm-debug.log

D:\Ratnadip\Projects\ecomm-gnc-sfcc\gulp_builder>nvm use 6.1.0

**Comment by trentm** [comment]
This was worked around by dropping testing of node v6 in #49. Later testing of the *latest* node v6 (not v6.0.0) was re-added in #53.   require-in-the-middle@6.0.0 (https://github.com/elastic/require-in-the-middle/pull/58) will be dropping support for node v6.
