### ISSUE TITLE
ES6 support when using import instead of require

### ISSUE THREAD

**Issue by subhranshudas** [elastic/require-in-the-middle#5]
Hi,

Is there any way we can use this package to use for ES6's import syntax? 

Thanks.

Regards,
Subhranshu

**Comment by watson** [comment]
Are you already using the experimental ESM support in Node.js or are you transpiling your code? We should work just fine with transpiled code as that will just use `require` after being transpiled.

But we will need to add support for native ESM at some point, but ESM support in Node.js is currently experimental and should not be used in production.

In any case, it should be possible for us add support for ESM by using a custom loader: https://nodejs.org/api/esm.html#esm_loader_hooks

**Comment by watson** [comment]
Closing this for now due to lack of activity. Feel free to comment if you think it should be re-opened 🙂

**Comment by skanygin** [comment]
I'm using [elastic-apm-node](https://www.npmjs.com/package/elastic-apm-node) in my app.  I depend on some es6 features and cannot (or may be it is possible but hard) to downgrade to `require` at every import usage. When bundling app APM is not working because imports not hooked [here](https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/index.js#L164). ESM support should fix this. Are there any plans to add ESM support?

node@14.3
express@4.17

**Comment by ebuildy** [comment]
Hello,

is it something planned? Or maybe a way to force the detection?

Thanks you,

**Comment by trentm** [comment]
Hi @ebuildy, yes supporting ES modules is on radar. I'm not positive it would land in *this* module as the mechanism for hooking into `import`s will be different. https://github.com/elastic/apm-agent-nodejs/issues/1952 is probably a better issue to use to track this.

**Comment by shikloshi** [comment]
+1
